#!/bin/bash
# strips all chars except . from hostname
dots=${1//[^.]}
sed "s/REPLACE_WITH_HOSTNAME/${1}/; s/REPLACE_WITH_CONTACT_EMAIL/${2}/" scripts/default_.env > .env
echo DEVISE_SECRET=`openssl rand -base64 48` >> .env
echo SECRET_COOKIE_TOKEN=`openssl rand -base64 48` >> .env
echo LOOMIO_CONTAINER_IMAGE=loomio/loomio >> .env
echo LOOMIO_CONTAINER_TAG=stable >> .env
echo MAILIN_CONTAINER_IMAGE=loomio/mailin-docker >> .env
echo MAILIN_CONTAINER_TAG=latest >> .env
echo POSTGRES_CONTAINER_TAG=12.2 >> .env
